### PR TITLE
Helper

### PR DESCRIPTION
**Pull request by aawdls**
This is my "shim" to add the required records

### CODE REVIEW

**Comment by aawdls** [comment]
Just realised a mistake, fixing

**Comment by T-Nicholls** [comment]
Thanks, I'm planning to implement a general mirroring system so records can mirror other records of the same type. I'll look at quadrupole offset from tune feedback afterwards as it is more complex.

**Comment by aawdls** [comment]
Cool. I've just fixed the mistake and introduced an extra hack to keep the tune PVs' timestamps updating

**Comment by T-Nicholls** [comment]
@aawdls 
The emittance conversion and the unit conv csv files edit are both available on my [unitConv](https://github.com/T-Nicholls/pytac/tree/unitConv) branch.

**Comment by T-Nicholls** [comment]
The full mirroring functionality should now be working on the master branch. From your point of view it should all just work automatically. As discussed today, everything but the refreshing of PVs to prevent timeouts has been implemented, but the server object does now have a `refresh_pv(pv_name)` method. I have tested everything and it seemed to work, but I am tentative as the backend is messy at the moment, so if your normal use of it picks up any problems let me know.

**Comment by aawdls** [comment]
It looks good, except for in tune feedback, the forwarding of the SQUAD offsets doens't seem to be updating. I'm afraid I can't quite remember what we discussed about the implementation of this one - do I still need to intervene to make them be applied?

**Comment by T-Nicholls** [comment]
I corrected the typos and other things we found today on the master branch.
I also created a new branch 'cagetless' which applies the offset without having to call caget. Could you please test this branch to see if it has fixed the tune feedback, if caget isn't the cause of the delay or if it doesn't work then I'll look into the problem more on Thursday.

**Comment by aawdls** [comment]
Thanks, I'll give that a go today 😎

________________________________

**Comment by aawdls** [comment]
On cagetless, when I do `server.start_tune_feedback()`, I get lots of exceptions like the below, and also once I turn the feedback on. Shall we have a look on Thrusday?

```

Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 314, in 'calling callback function'
  File "/dls_sw/prod/R3.14.12.3/support/pythonSoftIoc/2-11/python/softioc/device_core.py", line 132, in <lambda>
    cls.__call_instance_method(method, args, record_offset)
  File "/dls_sw/prod/R3.14.12.3/support/pythonSoftIoc/2-11/python/softioc/device_core.py", line 152, in __call_instance_method
    return method(self, *args)
  File "/dls_sw/prod/R3.14.12.3/support/pythonSoftIoc/2-11/python/softioc/device.py", line 57, in _process
    self._write_value(record, value)
  File "/dls_sw/prod/R3.14.12.3/support/pythonSoftIoc/2-11/python/softioc/device.py", line 31, in _write_value
    setattr(record, self._val_field_, value)
  File "/dls_sw/prod/R3.14.12.3/support/pythonSoftIoc/2-11/python/softioc/fields.py", line 150, in __setattr__
    cast(address, POINTER(ctypes_type))[0] = value
TypeError: int expected instead of float

```

________________________________

**Comment by T-Nicholls** [comment]
Closing because as of today all functionality required for feedback systems work is now in ATIP.

**Pull request closed without merging**
